# -*- coding: utf-8 -*-
"""ai6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eBHGDB1WXzRAcfZ1Ero5L29u67akUOgQ

Artificial Intelligence
---
**Practical 6** Naive Bayes Classification
"""

import numpy as np
from sklearn.naive_bayes import GaussianNB

# Features
X = np.array([
              [0, 0, 0, 0],
              [0, 0, 0, 1],
              [1, 0, 0, 0],
              [2, 1, 0, 0],
              [2, 2, 1, 0],
              [2, 2, 1, 1],
              [1, 2, 1, 1],
              [0, 1, 0, 0],
              [0, 2, 1, 0],
              [2, 1, 1, 0],
              [0, 1, 1, 1],
              [1, 1, 0, 1],
              [1, 0, 1, 0],
              [2, 1, 0, 1]
])
# Label
Y = np.array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

model = GaussianNB()
model.fit(X, Y)
print("prediction : ", end="")
if model.predict([[2, 0, 1, 0]])==1:
  print("YES")
else:
  print("NO")