# -*- coding: utf-8 -*-
"""ai7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-wgDzoc2LjdTgsewKKGVJI5Gdp2NCzoz

Artificial Intelligence
---
**Practical 7** Regression on House Prices Prediction
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# %matplotlib inline

customers = pd.read_csv('/content/house.csv')
customers.head(5)

customers.describe()
customers.info()

sns.pairplot(customers)

scaler = StandardScaler()

X=customers.drop(['Price','Address'],axis=1)
y=customers['Price']

cols = X.columns

X = scaler.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

lr = LinearRegression()
lr.fit(X_train,y_train)

pred = lr.predict(X_test)

r2_score(y_test,pred)


sns.scatterplot(x=y_test, y=pred)

sns.histplot((y_test-pred),bins=50,kde=True)

cdf=pd.DataFrame(lr.coef_, cols, ['coefficients']).sort_values('coefficients',ascending=False)
cdf